services:
  banking-service:
    image: pc/banking-service:1.0.0-SNAPSHOT
    container_name: banking-service-container
    environment:
      - QUARKUS_CLIENT_HTTP=host.docker.internal
      - QUARKUS_CLIENT_HTTP_PORT=${QUARKUS_CLIENT_HTTP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres-db-alura-banking-service
      - POSTGRES_PORT=5432
    ports:
      - 8080:8080
    depends_on:
      - postgres-db-alura-banking-service

  postgres-db-alura-banking-service:
    image: postgres:14
    container_name: postgres-db-alura-banking-service-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - 5433:5432